### ISSUE TITLE
Parsing json

### ISSUE THREAD

**Issue by tolgay007** [sraj/Swift-SRWebClient#6]
I am using your library, I have to parse this json:

{"status":1,"picture":"78bd35ede6f1f996c2d05b54de5a6278.jpg"}

I tried this code:
let headersJSON = response! as! Dictionary<String, String>
println(headersJSON["picture"]!)

But I am getting following error:

Could not cast value of type '__NSCFString' (0x1036f2c50) to 'NSDictionary' (0x1036f38d0).

How can I fix it ?

**Comment by sraj** [comment]
added fixes to work with latest swift changes, should work with latest update

**Comment by tolgay007** [comment]
Thank you, but I tried again but getting same problem with same code for same json. Is my json valid for this code ?

**Comment by sraj** [comment]
I tried to simulate your json like this,

let result = NSJSONSerialization.dataWithJSONObject(["status":1, "picture":"78bd35ede6f1f996c2d05b54de5a6278.jpg"], options: nil, error: nil)
let json:AnyObject? = NSJSONSerialization.JSONObjectWithData(result!, options: nil, error: &error)

and i sent it to the success handler, which i received in my test method and got parsed it as 

response["picture"] as! String

**Comment by tolgay007** [comment]
Sorry, my swift experiance is less. Could you explain more?

        SRWebClient.POST("url")
            .data(imageData, fieldName:"imagefile", data: ["username":self.username,"key":self.token])
            .send({(response:AnyObject!, status:Int) -> Void in
                /// I have to parse the json in here
                },failure:{(error:NSError!) -> Void in 
            })

How can I parse the json inside the response variable? Could you help?

**Comment by sraj** [comment]
SRWebClient.POST("url")
        .data(imageData, fieldName:"imagefile", data: ["username":self.username,"key":self.token])
        .send({(response:AnyObject!, status:Int) -> Void in
            println(response["picture"] as! String)
            },failure:{(error:NSError!) -> Void in 
        })

You don't have to parse json, it's already been converted to object when the Content-Type is application/json.

**Comment by tolgay007** [comment]
Thank you so much. It works well now.
